sudo: required

language: python

python:
    - "3.5"

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
    - cd docker
    - docker-compose up -d
    - docker ps
    - cd ..

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION libhdfs3 -c conda-forge
    - source activate test-environment
    - pip install -r requirements.txt .
    - docker network ls
    - docker network inspect docker_joblib_hadoop

script:
    # All examples/tests are run from a docker container
    - cd docker
    # HDFS store backend example
    - docker-compose run --rm --name testnode nodemanager python examples/joblib_hdfs_multiply.py
    # YARN parallel backend example
    - docker-compose run --rm --name testnode nodemanager python examples/joblib_yarn_parallel.py
    # Unit testing from root of project
    - docker-compose run --rm --name testnode -e NAMENODE=namenode nodemanager pytest
    - cd .. && pytest

after_success:
    - codecov

after_script:
    # Cleanup
    - docker-compose kill
    - docker-compose rm -f

notifications:
      email: false
