channels:
    - conda-forge
dependencies:
    - python=3.5
    - pip
    - libhdfs3
    - numpy
    - pip:
        - setuptools
        - git+https://github.com/dask/hdfs3.git@master#egg=hdfs3
        - git+https://github.com/joblib/joblib.git#egg=joblib
        - git+https://github.com/joblib/joblib-hadoop@master#egg=joblibhadoop
